name = "bences"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "733f8884fe9b92968bb63aac8843addf469df7edfa4ab4c7255ee9fe1ff2669d"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
