name = "bences"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91cff77e0aae03f3cf648884634dae605ca9fcf25a77ae80166f13f71ad030d3"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
